# Generated by Django 4.2.3 on 2024-10-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='last_restocked_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
